# Configuration file for Todo App
server:
  host: "localhost"
  port: "8000"
  swagger_url: "swagger/docs/index.html"

# Database mysql configuration
db:
  host: "localhost"
  port: "3306"
  username: "root"
  dbname: "todo_db"
  sslmode: "disable"
  parsetime: "true"

# Redis configuration
redis:
  host: "127.0.0.1:"
  port: "6379"
  user: ""
  db: 0
  maxretries: 5
  dialtimeout: 10s
  timeout: 5s
