port: "8000"

db:
  host: "localhost"
  port: "3306"
  username: "root"
  dbname: "todo_db"
  sslmode: "disable"
  parsetime: "true"

redis:
  host: "127.0.0.1"
  port: "6379"
  user: ""
  db: 0
  maxretries: 5
  dialtimeout: 10s
  timeout: 5s
